{
 "title": "BenMon Multi Host",
 "description": "【English version】Update 2020.10.10, add the overall resource overview! Support Grafana6&7,Support Node Exporter v0.16 and above.Optimize the main metrics display. Includes: CPU, memory, disk IO, network, temperature and other monitoring metrics。https://github.com/starsliao/Prometheus",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "origin_prometheus",
    "label": "Origin_prom",
    "query": "label_values(origin_prometheus)"
   },
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\"}, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "Instance",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "device",
    "label": "NIC",
    "query": "label_values(node_network_info{origin_prometheus=~\"$origin_prometheus\",device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
   },
   { "name": "disks", "label": "Disk Regex", "query": "nvm.*" },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "maxmount",
    "label": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",instance=~'$node',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
   },
   {
    "name": "show_hostname",
    "label": "show_hostname",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",instance=~\"$node\"}, nodename)"
   },
   {
    "name": "total",
    "label": "total_servers",
    "query": "query_result(count(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}))"
   }
  ]
 },
 "panels": [
  { "title": "Testing Tools Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Vdbench IO Profile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "sum(vdbench_rdpct)", "legendFormat": "Read%" },
    { "expr": "sum(vdbench_seekpct)", "legendFormat": "Random%" },
    { "expr": "sum by(run) (vdbench_xfersize)", "legendFormat": "Blk {{run}}" }
   ]
  },
  {
   "title": "Vdbench IO Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    { "expr": "sum(vdbench_rate)", "legendFormat": "Total IO" },
    {
     "expr": "sum(vdbench_rate) * (1 - sum(vdbench_rdpct/100))",
     "legendFormat": "Write IO"
    },
    {
     "expr": "sum(vdbench_rate) * sum(vdbench_rdpct/100)",
     "legendFormat": "Read IO"
    },
    { "expr": "sum(vdbench_write_resp)", "legendFormat": "Write Response" },
    { "expr": "sum(vdbench_read_resp)", "legendFormat": "Read Response" }
   ]
  },
  {
   "title": "Vdbench Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    { "expr": "sum(vdbench_mb_sec)", "legendFormat": "Total" },
    {
     "expr": "sum(vdbench_mb_sec) * (1 - sum(vdbench_rdpct/100))",
     "legendFormat": "Writes"
    },
    {
     "expr": "sum(vdbench_mb_sec) * sum(vdbench_rdpct/100)",
     "legendFormat": "Reads"
    },
    { "expr": "sum(vdbench_queue_depth)", "legendFormat": "Queue Depth" }
   ]
  },
  {
   "title": "Host Disk Overview (associated JOB)，Host：$show_hostname，Instance：$node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Overall Disk R/W Time Average",
   "type": "timeseries",
   "description": "Time spent on each read/write operation",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(avg(rate(node_disk_read_time_seconds_total{instance=~\"$node\", device=~\"$disks\"}[$interval])) / avg(rate(node_disk_reads_completed_total{instance=~\"$node\", device=~\"$disks\"}[$interval])) + avg(rate(node_disk_write_time_seconds_total{instance=~\"$node\", device=~\"$disks\"}[$interval])) / avg(rate(node_disk_writes_completed_total{instance=~\"$node\", device=~\"$disks\"}[$interval]))) /2",
     "legendFormat": "Total time"
    },
    {
     "expr": "avg(rate(node_disk_write_time_seconds_total{instance=~\"$node\", device=~\"$disks\"}[$interval])) / avg(rate(node_disk_writes_completed_total{instance=~\"$node\", device=~\"$disks\"}[$interval]))",
     "legendFormat": "Write time"
    },
    {
     "expr": "avg(rate(node_disk_read_time_seconds_total{instance=~\"$node\", device=~\"$disks\"}[$interval])) / avg(rate(node_disk_reads_completed_total{instance=~\"$node\", device=~\"$disks\"}[$interval]))",
     "legendFormat": "Read time"
    }
   ]
  },
  {
   "title": "Total Disk IOps Completed（IOPS）",
   "type": "timeseries",
   "description": "Read/write completions per second\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{instance=~\"$node\", device=~\"$disks\"}[$interval])) + sum(rate(node_disk_writes_completed_total{instance=~\"$node\", device=~\"$disks\"}[$interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(node_disk_writes_completed_total{instance=~\"$node\", device=~\"$disks\"}[$interval]))",
     "legendFormat": "Writes"
    },
    {
     "expr": "sum(rate(node_disk_reads_completed_total{instance=~\"$node\", device=~\"$disks\"}[$interval]))",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Total Disk R/W Throughput",
   "type": "timeseries",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=~\"$node\", device=~\"$disks\"}[$interval])) + sum(rate(node_disk_written_bytes_total{instance=~\"$node\", device=~\"$disks\"}[$interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=~\"$node\", device=~\"$disks\"}[$interval]))",
     "legendFormat": "Writes"
    },
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=~\"$node\", device=~\"$disks\"}[$interval]))",
     "legendFormat": "Reads"
    }
   ]
  },
  { "title": "Resource Usage by Instance:", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Disk R/W Time Average",
   "type": "timeseries",
   "description": "Time spent on each read/write operation",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(node_disk_read_time_seconds_total{instance=~\"$node\", device=~\"$disks\"}[$interval])) by (instance) / avg(rate(node_disk_reads_completed_total{instance=~\"$node\", device=~\"$disks\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}} {{device}}_Read time"
    },
    {
     "expr": "avg(rate(node_disk_write_time_seconds_total{instance=~\"$node\", device=~\"$disks\"}[$interval])) by (instance) / avg(rate(node_disk_writes_completed_total{instance=~\"$node\", device=~\"$disks\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}} {{device}}_Write time"
    }
   ]
  },
  {
   "title": "Disk IOps Completed（IOPS）",
   "type": "timeseries",
   "description": "Read/write completions per second\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{instance=~\"$node\", device=~\"$disks\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}_Reads"
    },
    {
     "expr": "sum(rate(node_disk_writes_completed_total{instance=~\"$node\", device=~\"$disks\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}_Writes"
    }
   ]
  },
  {
   "title": "Disk R/W Throughput",
   "type": "timeseries",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=~\"$node\", device=~\"$disks\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}_Reads"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=~\"$node\", device=~\"$disks\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}_Writes"
    }
   ]
  },
  {
   "title": "CPU% Total Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "{{instance}} Total Usage"
    }
   ]
  },
  {
   "title": "CPU% Processing vs IO Waiting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode!~\"idle|iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "{{instance}} Processing"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[$interval])) by (instance)*100",
     "legendFormat": "{{instance}}_IO_wait"
    }
   ]
  },
  {
   "title": "Disk Queue Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "targets": [
    {
     "expr": "avg(irate(node_disk_io_time_weighted_seconds_total{instance=~\"$node\",job=\"$job\", device=~\"$disks\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}} {{device}}_Queue"
    }
   ]
  },
  {
   "title": "Disk R/W Time",
   "type": "timeseries",
   "description": "Time spent on each read/write operation",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$node\", device=~\"$disks\"}[$interval]) / rate(node_disk_reads_completed_total{instance=~\"$node\", device=~\"$disks\"}[$interval])",
     "legendFormat": "{{instance}} {{device}}_Read"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$node\", device=~\"$disks\"}[$interval]) / rate(node_disk_writes_completed_total{instance=~\"$node\", device=~\"$disks\"}[$interval])",
     "legendFormat": "{{instance}} {{device}}_Write"
    }
   ]
  },
  {
   "title": "Network bandwidth usage per second $device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~'$node',device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{instance}}_{{device}}_receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~'$node',device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{instance}}_{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "{{instance}} - Mem Usage%"
    }
   ]
  },
  {
   "title": "Disk Space Used% Basic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*(pod|boot).*\"}))",
     "legendFormat": "{{instance}} {{mountpoint}}"
    }
   ]
  }
 ]
}